[project]
name = "omnipack"
version = "0.1.0"
description = "3D Bin Packing Optimization Engine"
readme = "README.md"
authors = [
    { name = "Matteo", email = "matteo.griot@gmail.com" }
]
license = {file = "LICENSE"}
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.103.2",
    "pydantic<2.0.0",
    "httpx<0.28.0",
    "numpy>=1.26.2",
    "pytest>=9.0.2",
    "uvicorn>=0.41.0",
]

[tool.briefcase]
project_name = "OmniPack"
bundle = "com.omnipack"
version = "0.1.0"
url = "https://github.com/omnipack/omnipack"
author = "Matteo"
author_email = "matteo.griot@gmail.com"
[tool.briefcase.app.omnipack]
formal_name = "OmniPack"
description = "3D Bin Packing Engine"
sources = ["src/omnipack"]
requires = [
    "numpy",
]
build_gradle_dependencies = [
    "androidx.appcompat:appcompat:1.0.2",
    "androidx.constraintlayout:constraintlayout:1.1.3",
    "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0",
    "androidx.webkit:webkit:1.4.0",
]

[tool.briefcase.app.omnipack.macOS]
universal_build = true
requires = [
    "toga-cocoa>=0.5.3",
]

[tool.briefcase.app.omnipack.windows]
requires = [
    "toga-winforms>=0.5.3",
]

[tool.briefcase.app.omnipack.linux]
requires = [
    "toga-gtk>=0.5.3",
]

[tool.briefcase.app.omnipack.android]
requires = [
    "toga-android>=0.5.3",
]
cleartext_traffic = true

[tool.briefcase.app.omnipack.iOS]
requires = [
    "toga-iOS>=0.5.3",
]

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "briefcase>=0.3.26",
    "maturin>=1.12.6",
    "toga>=0.5.3",
]
