package com.omnipack.omnipack;

import android.webkit.JavascriptInterface;
import com.chaquo.python.PyObject;
import com.chaquo.python.Python;

/**
 * JS<->Python bridge for the Android build. Android's WebResourceRequest
 * (used by shouldInterceptRequest) exposes no way to read a POST body, so
 * unlike the Windows build we can't intercept viewer.html's fetch() calls
 * in-process. Instead viewer.html calls window.OmniPackAndroid.call(...)
 * directly (see the api() function's Android branch), which reaches this
 * class via addJavascriptInterface, which calls straight into
 * omnipack.bridge.dispatch_json (no server, no port, no HTTP semantics at
 * all - just a synchronous Java call into Python via Chaquopy).
 *
 * NOT auto-generated by Briefcase/Chaquopy - `briefcase create android`
 * only manages Python sources, not custom Java. If the android/ project is
 * ever regenerated, copy this file back to
 * build/omnipack/android/gradle/app/src/main/java/com/omnipack/omnipack/
 * (see docs/ANDROID_GUIDE.md).
 */
public class OmniPackBridge {
    @JavascriptInterface
    public String call(String path, String method, String body) {
        Python py = Python.getInstance();
        PyObject module = py.getModule("omnipack.bridge");
        PyObject result = module.callAttr("dispatch_json", path, method, body);
        return result.toString();
    }
}
