import numpy as np
from typing import List, Tuple, Set
from .models import Item, Container, Rotation
from .ep import ExtremePoint, generate_extreme_points, get_valid_ep

class Level2Engine:
    """
    PC/Workstation Engine: Uses Numba JIT and Parallel loops.
    Optimized for floor utilization and space discovery.
    """
    def __init__(self, container: Container):
        self.container = container
        # Use a dictionary to keep track of points and their scores if needed
        self.extreme_points: Set[ExtremePoint] = {ExtremePoint(0, 0, 0)}

    def pack(self, items: List[Item]) -> List[Item]:
        # 1. Sort items by volume descending (standard heuristic)
        sorted_items = sorted(items, key=lambda x: x.volume(), reverse=True)
        unpacked_items = []

        for item in sorted_items:
            # Prepare data for parallel evaluation
            eps_list = list(self.extreme_points)
            eps_array = np.array([[p.x, p.y, p.z] for p in eps_list], dtype=np.float64)
            
            rots = []
            orig_rot = item.rotation
            for rot in Rotation:
                item.rotation = rot
                rots.append(item.get_dimension())
            item.rotation = orig_rot
            rots_array = np.array(rots, dtype=np.float64)

            existing_pos = np.array([i.position for i in self.container.items], dtype=np.float64).reshape(-1, 3)
            existing_dim = np.array([i.get_dimension() for i in self.container.items], dtype=np.float64).reshape(-1, 3)
            existing_weights = np.array([i.weight for i in self.container.items], dtype=np.float64)
            existing_max_support = np.array([i.max_stack_weight for i in self.container.items], dtype=np.float64)
            
            container_dim = np.array([self.container.width, self.container.height, self.container.depth], dtype=np.float64)

            # Parallel verification of all possible placements
            valid_mask = evaluate_positions_parallel(
                eps_array, rots_array, existing_pos, existing_dim, 
                existing_weights, existing_max_support, container_dim, item.weight
            )
            
            best_fit = None # (EP_idx, Rot_idx, Score)
            
            for i in range(len(eps_list)):
                for j in range(6):
                    if valid_mask[i, j]:
                        ep = eps_list[i]
                        # Score: Z first (Floor), then Y (Back), then X (Left)
                        score = (ep.z, ep.y, ep.x)
                        
                        if best_fit is None or score < best_fit[2]:
                            best_fit = (i, j, score)
            
            if best_fit:
                ep_idx, rot_idx, _ = best_fit
                ep = eps_list[ep_idx]
                item.position = ep.to_tuple()
                item.rotation = Rotation(rot_idx)
                
                # Add item to container
                self.container.items.append(item)
                
                # Update Extreme Points
                # We remove the used point and generate NEW ones from the new item
                self.extreme_points.remove(ep)
                new_eps = generate_extreme_points(self.container, item)
                for nep in new_eps:
                    # Before adding, ensure it's not already inside another item 
                    # (Simplified check: if it was generated by the enhanced logic, it's valid)
                    self.extreme_points.add(nep)
            else:
                unpacked_items.append(item)
                
        return unpacked_items
