from typing import List, Tuple, Set
from .models import Item, Container

class ExtremePoint:
    def __init__(self, x: float, y: float, z: float):
        self.x = x
        self.y = y
        self.z = z

    def to_tuple(self) -> Tuple[float, float, float]:
        return (self.x, self.y, self.z)

    def __eq__(self, other):
        if not isinstance(other, ExtremePoint):
            return False
        return self.x == other.x and self.y == other.y and self.z == other.z

    def __hash__(self):
        return hash((self.x, self.y, self.z))

def generate_extreme_points(container: Container, item: Item) -> List[ExtremePoint]:
    """
    Generates new extreme points based on a newly placed item.
    Following Crainic et al. (2000) logic.
    """
    w, h, d = item.get_dimension()
    x, y, z = item.position

    # 6 potential EPs generated by a placed box (simplification for Level 1)
    # In a more advanced version, we project these onto existing surfaces.
    pts = [
        ExtremePoint(x + w, y, z),
        ExtremePoint(x, y + h, z),
        ExtremePoint(x, y, z + d)
    ]
    
    # Filter points outside container
    valid_pts = []
    for p in pts:
        if p.x < container.width and p.y < container.height and p.z < container.depth:
            valid_pts.append(p)
            
    return valid_pts

def get_valid_ep(container: Container, item: Item, eps: Set[ExtremePoint]) -> List[ExtremePoint]:
    """Returns EPs where the item can be placed without collision."""
    valid_eps = []
    w, h, d = item.get_dimension()
    
    for ep in eps:
        # Check container boundaries
        if (ep.x + w <= container.width and 
            ep.y + h <= container.height and 
            ep.z + d <= container.depth):
            
            # Check collision with existing items
            collision = False
            for other in container.items:
                ow, oh, od = other.get_dimension()
                ox, oy, oz = other.position
                
                # AABB Collision
                if (ep.x < ox + ow and ep.x + w > ox and
                    ep.y < oy + oh and ep.y + h > oy and
                    ep.z < oz + od and ep.z + d > oz):
                    collision = True
                    break
            
            if not collision:
                valid_eps.append(ep)
                
    return valid_eps
