[package]
name = "omnipack-app"
description = "OmniPack desktop and mobile app"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "omnipack_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
omnipack-core.workspace = true
omnipack-geom.workspace = true
omnipack-opt.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde.workspace = true
serde_json.workspace = true
